# project level configuration
#docker: java-docker

cache: true
build_path: ./project_folder_name
env:
 - FLOW_ENV_1=xxx111,FLOW_ENV_2=xxx111
 - FLOW_ENV_3=xxx222
 - FLOW_ENV_4=xxx333

# flow level configuration
flows:
  - name: 123
#    docker: open-jdk-1.9-docker
#    language: objective-c
    language: ruby
    version: 2.3.0
    cache: false
    env:
      - FLOW_ENV_5=xxx555
      - FLOW_ENV_6=xxx666

    trigger:
      push:
#        - develop
        - master
      tag:
        - '*'
      pull_request: true
      schedule:
        - 5, 5, 10, 10

    finalize:
      email:
        success:
          - hl@fir.im
        failure:
          - hl@fir.im
      slack:
        success:
          - https://hooks.slack.com/services/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
        failure:
          - https://hooks.slack.com/services/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
#      webhook:
#        success:
#          - http://www1.slack.com/
#        failure:
#          - http://www.slack.com/

    # steps definition, cannot define both plugin and scripts
    steps:
      - name: step_0
        enable: true
        failure: true
        plugin:
#          name: nodejs_init
          name: ruby_init
          inputs:
            - FLOW_WORK_SPACE=12
            - FLOW_WORK_XXXXX=14

      - name: step_1
        failure: true
        scripts:
          - echo "hello world1"

      - name: step_3 # only plugin
        plugin:
          name: mongodb_database
#          version: 2.3.6

      - name: step_4 # only script
        scripts:
          - echo "hello world1"
          - echo "hello world2"
      - name: step_5 # only script
        scripts:
          - echo "hello world1"
          - echo "hello world2"
      - name: step_6 # only script
        scripts:
          - echo "hello world1"
          - echo "hello world2"
      - name: step_7 # only script
        scripts:
          - echo "hello world1"
          - echo "hello world2"
      - name: step_8 # only script
        scripts:
          - echo "hello world1"
          - echo "hello world2"
      - name: step_9 # only script
        scripts:
          - echo "hello world1"
          - echo "hello world2"

#  - name: flow-2
#    trigger:
#      push:
#        - develop

    # steps definition, cannot define both plugin and scripts
#    steps:
#      - name: step_1
#        enable: true
#        failure: false
#        plugin:
#          name: android_init
#          inputs:
#            - FLOW_WORK_SPACE=12
#            - FLOW_WORK_XXXXX=14